### ISSUE TITLE
How to deploy smartcontracts?

### ISSUE THREAD

**Issue by 0x00trust** [proyecto26/thecryptopurge#5]
Hello,
I'm newbie
I'm install for localhost
The app website run
http://localhost:3000
Server listenting on 8081
But cannot know
How to deploy smartcontracts? for testnet
The metamask addon was installed
Please make some guide
Thank and regards
```
https://pasteboard.co/XVvYKktD0RNw.png
https://pasteboard.co/uYX5HwQkenHQ.png
https://pasteboard.co/zmtFjGtfSmta.png
https://pasteboard.co/tqBEJwSfEmWL.png
```

**Comment by jdnichollsc** [comment]
Hey @0x00trust, hope you're doing well

We are not maintaining the contracts in this repository anymore, the development is still in private projects, in this repo we are going to have only the website configuration for public visibility <3

Best Regards,
Juan
